apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: misthalin

resources:
  - service.yaml
  - http-route.yaml
  - deployment.yaml

configMapGenerator:
  - name: hello-spk-html
    namespace: misthalin
    files:
      - index.html
      - styles.css

